name: Test_and_build_artifacts_on_debug

on:
  push:
    branches:
      - 'master'

jobs:
  build_apk_aab:
    name: Build debug artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 17}
      - name: Build debug APK and AAB after test
        run: |
          ./gradlew test
          ./gradlew assembleDebug
          ./gradlew bundleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug-unsigned.apk
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/app-debug.aab