name: Android Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script-path: ${{ runner.workspace }}/scripts/start-emulator.sh
          state-path: ${{ runner.workspace }}/scripts/state.yml

      - name: Build and run tests
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew connectedAndroidTest
